// --- Auto Generated by BanTanger ---
package com.bantanger.domain.template.objecttemplate.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.template.objecttemplate.creator.TemplateCategoryCreator;
import com.bantanger.domain.template.objecttemplate.query.TemplateCategoryQuery;
import com.bantanger.domain.template.objecttemplate.updater.TemplateCategoryUpdater;
import com.bantanger.domain.template.objecttemplate.vo.TemplateCategoryVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ITemplateCategoryService {
   /**
    * create
    */
   Long createTemplateCategory(TemplateCategoryCreator creator);

   /**
    * update
    */
   void updateTemplateCategory(TemplateCategoryUpdater updater);

   /**
    * valid
    */
   void validTemplateCategory(Long id);

   /**
    * invalid
    */
   void invalidTemplateCategory(Long id);

   /**
    * findById
    */
   TemplateCategoryVO findById(Long id);

   /**
    * findByPage
    */
   Page<TemplateCategoryVO> findByPage(PageRequestWrapper<TemplateCategoryQuery> query);
}
