// --- Auto Generated by BanTanger ---
package com.bantanger.api.asset.record.request;

import com.bantanger.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;

@Schema
public class AssetInOutRecordUpdateRequest implements Request {
   @Schema(
         title = "手动录入批次号,仅用于展示"
   )
   private String batchNo;

   @Schema(
         title = "自动生成的批次号，防止重复"
   )
   private String genBatchNo;

   @Schema(
         title = "出入库业务类型"
   )
   private Integer inOutBizType;

   @Schema(
         title = "出入库类型"
   )
   private Integer inOutType;

   @Schema(
         title = "总数量"
   )
   private Integer totalCount;

   @Schema(
         title = "操作人"
   )
   private String operateUser;

   private Long id;

   public String getBatchNo() {
      return batchNo;
   }

   public void setBatchNo(String batchNo) {
      this.batchNo = batchNo;
   }

   public String getGenBatchNo() {
      return genBatchNo;
   }

   public void setGenBatchNo(String genBatchNo) {
      this.genBatchNo = genBatchNo;
   }

   public Integer getInOutBizType() {
      return inOutBizType;
   }

   public void setInOutBizType(Integer inOutBizType) {
      this.inOutBizType = inOutBizType;
   }

   public Integer getInOutType() {
      return inOutType;
   }

   public void setInOutType(Integer inOutType) {
      this.inOutType = inOutType;
   }

   public Integer getTotalCount() {
      return totalCount;
   }

   public void setTotalCount(Integer totalCount) {
      this.totalCount = totalCount;
   }

   public String getOperateUser() {
      return operateUser;
   }

   public void setOperateUser(String operateUser) {
      this.operateUser = operateUser;
   }

   public Long getId() {
      return id;
   }

   public void setId(long id) {
      this.id = id;
   }
}
