// --- Auto Generated by BanTanger ---
package com.bantanger.api.template.verifyrule.request;

import com.bantanger.common.model.Request;
import com.bantanger.common.verifyrule.VerifyRule;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;
import java.util.List;

@Schema
public class VerifyRuleConfigUpdateRequest implements Request {
   @Schema(
         title = "校验规则名称"
   )
   private String name;

   @Schema(
         title = "对应模板项ID"
   )
   private Long itemId;

   @Schema(
         title = "描述信息"
   )
   private String desc;

   @Schema(
         title = "校验规则配置列表"
   )
   private List<VerifyRule> ruleList;

   private Long id;

   public String getName() {
      return name;
   }

   public void setName(String name) {
      this.name = name;
   }

   public Long getItemId() {
      return itemId;
   }

   public void setItemId(Long itemId) {
      this.itemId = itemId;
   }

   public String getDesc() {
      return desc;
   }

   public void setDesc(String desc) {
      this.desc = desc;
   }

   public List<VerifyRule> getRuleList() {
      return ruleList;
   }

   public void setRuleList(List<VerifyRule> ruleList) {
      this.ruleList = ruleList;
   }

   public Long getId() {
      return id;
   }

   public void setId(long id) {
      this.id = id;
   }
}
