// --- Auto Generated by BanTanger ---
package com.bantanger.api.template.verifyrule.request;

import com.bantanger.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class VerifyRuleConfigQueryRequest implements Request {
}
