// --- Auto Generated by BanTanger ---
package com.bantanger.domain.permission.role.mapper;

import com.bantanger.api.permission.role.request.RoleCreateRequest;
import com.bantanger.api.permission.role.request.RoleQueryRequest;
import com.bantanger.api.permission.role.request.RoleUpdateRequest;
import com.bantanger.api.permission.role.response.RoleResponse;
import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.domain.permission.role.Role;
import com.bantanger.domain.permission.role.creator.RoleCreator;
import com.bantanger.domain.permission.role.query.RoleQuery;
import com.bantanger.domain.permission.role.updater.RoleUpdater;
import com.bantanger.domain.permission.role.vo.RoleVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
      uses = {
            GenericEnumMapper.class,
            DateMapper.class
      }
)
public interface RoleMapper {
   RoleMapper INSTANCE = Mappers.getMapper(RoleMapper.class);

   Role dtoToEntity(RoleCreator dto);

   RoleUpdater request2Updater(RoleUpdateRequest request);

   RoleCreator request2Dto(RoleCreateRequest request);

   RoleQuery request2Query(RoleQueryRequest request);

   RoleResponse vo2Response(RoleVO vo);

   default RoleResponse vo2CustomResponse(RoleVO vo) {
      RoleResponse response = vo2Response(vo);
      return response;
   }
}
