// --- Auto Generated by BanTanger ---
package com.bantanger.codegen.response;

import com.bantanger.common.enums.ValidStatus;
import com.bantanger.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.String;

@Schema
public class StudentResponse extends AbstractJpaResponse {
   @Schema(
         title = "用户名称"
   )
   private String name;

   @Schema(
         title = "用户年龄"
   )
   private Integer age;

   @Schema(
         title = "用户地址"
   )
   private String address;

   @Schema(
         title = "用户电话"
   )
   private String phone;

   @Schema(
         title = "用户邮箱"
   )
   private String email;

   @Schema(
         title = "validStatus"
   )
   private ValidStatus validStatus;

   public String getName() {
      return name;
   }

   public void setName(String name) {
      this.name = name;
   }

   public Integer getAge() {
      return age;
   }

   public void setAge(Integer age) {
      this.age = age;
   }

   public String getAddress() {
      return address;
   }

   public void setAddress(String address) {
      this.address = address;
   }

   public String getPhone() {
      return phone;
   }

   public void setPhone(String phone) {
      this.phone = phone;
   }

   public String getEmail() {
      return email;
   }

   public void setEmail(String email) {
      this.email = email;
   }

   public ValidStatus getValidStatus() {
      return validStatus;
   }

   public void setValidStatus(ValidStatus validStatus) {
      this.validStatus = validStatus;
   }
}
