// --- Auto Generated by BanTanger ---
package com.bantanger.domain.template.templateitem.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.template.templateitem.creator.TemplateItemCreator;
import com.bantanger.domain.template.templateitem.query.TemplateItemQuery;
import com.bantanger.domain.template.templateitem.updater.TemplateItemUpdater;
import com.bantanger.domain.template.templateitem.vo.TemplateItemVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ITemplateItemService {
   /**
    * create
    */
   Long createTemplateItem(TemplateItemCreator creator);

   /**
    * update
    */
   void updateTemplateItem(TemplateItemUpdater updater);

   /**
    * valid
    */
   void validTemplateItem(Long id);

   /**
    * invalid
    */
   void invalidTemplateItem(Long id);

   /**
    * findById
    */
   TemplateItemVO findById(Long id);

   /**
    * findByPage
    */
   Page<TemplateItemVO> findByPage(PageRequestWrapper<TemplateItemQuery> query);
}
