// --- Auto Generated by BanTanger ---
package com.bantanger.domain.template.templateitem.service;

import com.bantanger.common.enums.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.template.templateitem.TemplateItem;
import com.bantanger.domain.template.templateitem.creator.TemplateItemCreator;
import com.bantanger.domain.template.templateitem.mapper.TemplateItemMapper;
import com.bantanger.domain.template.templateitem.query.TemplateItemQuery;
import com.bantanger.domain.template.templateitem.repository.TemplateItemRepository;
import com.bantanger.domain.template.templateitem.updater.TemplateItemUpdater;
import com.bantanger.domain.template.templateitem.vo.TemplateItemVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class TemplateItemServiceImpl implements ITemplateItemService {
   private final TemplateItemRepository templateItemRepository;

   /**
    * createImpl
    */
   @Override
   public Long createTemplateItem(TemplateItemCreator creator) {
      Optional<TemplateItem> templateItem = EntityOperations.doCreate(templateItemRepository)
      .create(() -> TemplateItemMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return templateItem.isPresent() ? templateItem.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateTemplateItem(TemplateItemUpdater updater) {
      EntityOperations.doUpdate(templateItemRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateTemplateItem(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validTemplateItem(Long id) {
      EntityOperations.doUpdate(templateItemRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidTemplateItem(Long id) {
      EntityOperations.doUpdate(templateItemRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public TemplateItemVO findById(Long id) {
      Optional<TemplateItem> templateItem =  templateItemRepository.findById(id);
      return new TemplateItemVO(templateItem.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<TemplateItemVO> findByPage(PageRequestWrapper<TemplateItemQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<TemplateItem> page = templateItemRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(TemplateItemVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
