// --- Auto Generated by BanTanger ---
package com.bantanger.domain.permission.resource.mapper;

import com.bantanger.api.permission.resource.request.ResourceCreateRequest;
import com.bantanger.api.permission.resource.request.ResourceQueryRequest;
import com.bantanger.api.permission.resource.request.ResourceUpdateRequest;
import com.bantanger.api.permission.resource.response.ResourceResponse;
import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.domain.CustomMapper;
import com.bantanger.domain.permission.resource.Resource;
import com.bantanger.domain.permission.resource.creator.ResourceCreator;
import com.bantanger.domain.permission.resource.query.ResourceQuery;
import com.bantanger.domain.permission.resource.updater.ResourceUpdater;
import com.bantanger.domain.permission.resource.vo.ResourceVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class,
        CustomMapper.class
    }
)
public interface ResourceMapper {

    ResourceMapper INSTANCE = Mappers.getMapper(ResourceMapper.class);

    Resource dtoToEntity(ResourceCreator dto);

    ResourceUpdater request2Updater(ResourceUpdateRequest request);

    ResourceCreator request2Dto(ResourceCreateRequest request);

    ResourceQuery request2Query(ResourceQueryRequest request);

    ResourceResponse vo2Response(ResourceVO vo);

    default ResourceResponse vo2CustomResponse(ResourceVO vo) {
        ResourceResponse response = vo2Response(vo);
        return response;
    }
}
