// --- Auto Generated by BanTanger ---
package com.bantanger.api.asset.warehouse.response;

import com.bantanger.common.enums.ValidStatus;
import com.bantanger.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.String;

@Schema
public class WarehouseResponse extends AbstractJpaResponse {
   @Schema(
         title = "仓库名称"
   )
   private String name;

   @Schema(
         title = "仓库编码"
   )
   private String code;

   @Schema(
         title = "仓库地址"
   )
   private String address;

   @Schema(
         title = "创建人"
   )
   private String createUser;

   @Schema(
         title = "validStatus"
   )
   private ValidStatus validStatus;

   public String getName() {
      return name;
   }

   public void setName(String name) {
      this.name = name;
   }

   public String getCode() {
      return code;
   }

   public void setCode(String code) {
      this.code = code;
   }

   public String getAddress() {
      return address;
   }

   public void setAddress(String address) {
      this.address = address;
   }

   public String getCreateUser() {
      return createUser;
   }

   public void setCreateUser(String createUser) {
      this.createUser = createUser;
   }

   public ValidStatus getValidStatus() {
      return validStatus;
   }

   public void setValidStatus(ValidStatus validStatus) {
      this.validStatus = validStatus;
   }
}
