// --- Auto Generated by BanTanger ---
package com.bantanger.domain.stock.seat.mapper;

import com.bantanger.api.stock.seat.request.SeatStockDetailCreateRequest;
import com.bantanger.api.stock.seat.request.SeatStockDetailQueryRequest;
import com.bantanger.api.stock.seat.request.SeatStockDetailUpdateRequest;
import com.bantanger.api.stock.seat.response.SeatStockDetailResponse;
import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.domain.CustomMapper;
import com.bantanger.domain.stock.seat.SeatStockDetail;
import com.bantanger.domain.stock.seat.creator.SeatStockDetailCreator;
import com.bantanger.domain.stock.seat.query.SeatStockDetailQuery;
import com.bantanger.domain.stock.seat.updater.SeatStockDetailUpdater;
import com.bantanger.domain.stock.seat.vo.SeatStockDetailVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
        uses = {
                GenericEnumMapper.class,
                DateMapper.class,
                CustomMapper.class
        }
)
public interface SeatStockDetailMapper {
    SeatStockDetailMapper INSTANCE = Mappers.getMapper(SeatStockDetailMapper.class);

    SeatStockDetail dtoToEntity(SeatStockDetailCreator dto);

    SeatStockDetailUpdater request2Updater(SeatStockDetailUpdateRequest request);

    SeatStockDetailCreator request2Dto(SeatStockDetailCreateRequest request);

    SeatStockDetailQuery request2Query(SeatStockDetailQueryRequest request);

    SeatStockDetailResponse vo2Response(SeatStockDetailVO vo);

    default SeatStockDetailResponse vo2CustomResponse(SeatStockDetailVO vo) {
        SeatStockDetailResponse response = vo2Response(vo);
        return response;
    }
}
