// --- Auto Generated by BanTanger ---
package com.bantanger.codegen.service;

import com.bantanger.codegen.creator.StudentCreator;
import com.bantanger.codegen.query.StudentQuery;
import com.bantanger.codegen.updater.StudentUpdater;
import com.bantanger.codegen.vo.StudentVO;
import com.bantanger.common.model.PageRequestWrapper;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IStudentService {
   /**
    * create
    */
   Long createStudent(StudentCreator creator);

   /**
    * update
    */
   void updateStudent(StudentUpdater updater);

   /**
    * valid
    */
   void validStudent(Long id);

   /**
    * invalid
    */
   void invalidStudent(Long id);

   /**
    * findById
    */
   StudentVO findById(Long id);

   /**
    * findByPage
    */
   Page<StudentVO> findByPage(PageRequestWrapper<StudentQuery> query);
}
