// --- Auto Generated by BanTanger ---
package com.bantanger.domain.message.verify.mapper;

import com.bantanger.api.message.verify.request.VerifyRecordCreateRequest;
import com.bantanger.api.message.verify.request.VerifyRecordQueryRequest;
import com.bantanger.api.message.verify.request.VerifyRecordUpdateRequest;
import com.bantanger.api.message.verify.response.VerifyRecordResponse;
import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.domain.message.verify.VerifyRecord;
import com.bantanger.domain.message.verify.creator.VerifyRecordCreator;
import com.bantanger.domain.message.verify.query.VerifyRecordQuery;
import com.bantanger.domain.message.verify.updater.VerifyRecordUpdater;
import com.bantanger.domain.message.verify.vo.VerifyRecordVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
      uses = {
            GenericEnumMapper.class,
            DateMapper.class
      }
)
public interface VerifyRecordMapper {
   VerifyRecordMapper INSTANCE = Mappers.getMapper(VerifyRecordMapper.class);

   VerifyRecord dtoToEntity(VerifyRecordCreator dto);

   VerifyRecordUpdater request2Updater(VerifyRecordUpdateRequest request);

   VerifyRecordCreator request2Dto(VerifyRecordCreateRequest request);

   VerifyRecordQuery request2Query(VerifyRecordQueryRequest request);

   VerifyRecordResponse vo2Response(VerifyRecordVO vo);

   default VerifyRecordResponse vo2CustomResponse(VerifyRecordVO vo) {
      VerifyRecordResponse response = vo2Response(vo);
      return response;
   }
}
