// --- Auto Generated by BanTanger ---
package com.bantanger.domain.template.templateitem.repository;

import com.bantanger.domain.template.templateitem.TemplateItem;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface TemplateItemRepository extends BaseRepository<TemplateItem, Long> {
}
