// --- Auto Generated by BanTanger ---
package com.bantanger.api.template.templateitem.request;

import com.bantanger.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.String;

@Schema
public class TemplateItemQueryRequest implements Request {
   @Schema(
         title = "模板项名称"
   )
   private String name;

   public String getName() {
      return name;
   }

   public void setName(String name) {
      this.name = name;
   }
}
