// --- Auto Generated by BanTanger ---
package com.bantanger.domain.admin.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.admin.creator.AdminUserCreator;
import com.bantanger.domain.admin.query.AdminUserQuery;
import com.bantanger.domain.admin.updater.AdminUserUpdater;
import com.bantanger.domain.admin.vo.AdminUserVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IAdminUserService {
   /**
    * create
    */
   Long createAdminUser(AdminUserCreator creator);

   /**
    * update
    */
   void updateAdminUser(AdminUserUpdater updater);

   /**
    * valid
    */
   void validAdminUser(Long id);

   /**
    * invalid
    */
   void invalidAdminUser(Long id);

   /**
    * findById
    */
   AdminUserVO findById(Long id);

   /**
    * findByPage
    */
   Page<AdminUserVO> findByPage(PageRequestWrapper<AdminUserQuery> query);
}
