// --- Auto Generated by BanTanger ---
package com.bantanger.domain.permission.resource.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.permission.resource.creator.ResourceCreator;
import com.bantanger.domain.permission.resource.query.ResourceQuery;
import com.bantanger.domain.permission.resource.updater.ResourceUpdater;
import com.bantanger.domain.permission.resource.vo.ResourceVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IResourceService {
   /**
    * create
    */
   Long createResource(ResourceCreator creator);

   /**
    * update
    */
   void updateResource(ResourceUpdater updater);

   /**
    * valid
    */
   void validResource(Long id);

   /**
    * invalid
    */
   void invalidResource(Long id);

   /**
    * findById
    */
   ResourceVO findById(Long id);

   /**
    * findByPage
    */
   Page<ResourceVO> findByPage(PageRequestWrapper<ResourceQuery> query);
}
