// --- Auto Generated by BanTanger ---
package com.bantanger.domain.stock.seat.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.stock.seat.creator.SeatStockDetailCreator;
import com.bantanger.domain.stock.seat.query.SeatStockDetailQuery;
import com.bantanger.domain.stock.seat.updater.SeatStockDetailUpdater;
import com.bantanger.domain.stock.seat.vo.SeatStockDetailVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ISeatStockDetailService {
   /**
    * create
    */
   Long createSeatStockDetail(SeatStockDetailCreator creator);

   /**
    * update
    */
   void updateSeatStockDetail(SeatStockDetailUpdater updater);

   /**
    * valid
    */
   void validSeatStockDetail(Long id);

   /**
    * invalid
    */
   void invalidSeatStockDetail(Long id);

   /**
    * findById
    */
   SeatStockDetailVO findById(Long id);

   /**
    * findByPage
    */
   Page<SeatStockDetailVO> findByPage(PageRequestWrapper<SeatStockDetailQuery> query);
}
