// --- Auto Generated by BanTanger ---
package com.bantanger.domain.stock.seat.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.stock.seat.creator.SeatStockCreator;
import com.bantanger.domain.stock.seat.query.SeatStockQuery;
import com.bantanger.domain.stock.seat.updater.SeatStockUpdater;
import com.bantanger.domain.stock.seat.vo.SeatStockVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ISeatStockService {
   /**
    * create
    */
   Long createSeatStock(SeatStockCreator creator);

   /**
    * update
    */
   void updateSeatStock(SeatStockUpdater updater);

   /**
    * valid
    */
   void validSeatStock(Long id);

   /**
    * invalid
    */
   void invalidSeatStock(Long id);

   /**
    * findById
    */
   SeatStockVO findById(Long id);

   /**
    * findByPage
    */
   Page<SeatStockVO> findByPage(PageRequestWrapper<SeatStockQuery> query);
}
