// --- Auto Generated by BanTanger ---
package com.bantanger.domain.stock.seat.service;

import com.bantanger.common.enums.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.stock.seat.SeatStock;
import com.bantanger.domain.stock.seat.creator.SeatStockCreator;
import com.bantanger.domain.stock.seat.mapper.SeatStockMapper;
import com.bantanger.domain.stock.seat.query.SeatStockQuery;
import com.bantanger.domain.stock.seat.repository.SeatStockRepository;
import com.bantanger.domain.stock.seat.updater.SeatStockUpdater;
import com.bantanger.domain.stock.seat.vo.SeatStockVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class SeatStockServiceImpl implements ISeatStockService {
   private final SeatStockRepository seatStockRepository;

   /**
    * createImpl
    */
   @Override
   public Long createSeatStock(SeatStockCreator creator) {
      Optional<SeatStock> seatStock = EntityOperations.doCreate(seatStockRepository)
      .create(() -> SeatStockMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return seatStock.isPresent() ? seatStock.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateSeatStock(SeatStockUpdater updater) {
      EntityOperations.doUpdate(seatStockRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateSeatStock(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validSeatStock(Long id) {
      EntityOperations.doUpdate(seatStockRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidSeatStock(Long id) {
      EntityOperations.doUpdate(seatStockRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public SeatStockVO findById(Long id) {
      Optional<SeatStock> seatStock =  seatStockRepository.findById(id);
      return new SeatStockVO(seatStock.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<SeatStockVO> findByPage(PageRequestWrapper<SeatStockQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<SeatStock> page = seatStockRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(SeatStockVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
