// --- Auto Generated by BanTanger ---
package com.bantanger.domain.trade.orderitem.repository;

import com.bantanger.domain.trade.orderitem.OrderItem;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface OrderItemRepository extends BaseRepository<OrderItem, Long> {
}
