// --- Auto Generated by BanTanger ---
package com.bantanger.domain.template.verifyrule.repository;

import com.bantanger.domain.template.verifyrule.VerifyRuleConfig;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface VerifyRuleConfigRepository extends BaseRepository<VerifyRuleConfig, Long> {
}
