// --- Auto Generated by BanTanger ---
package com.bantanger.domain.message.verify.service;

import com.bantanger.common.constants.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.message.verify.VerifyRecord;
import com.bantanger.domain.message.verify.creator.VerifyRecordCreator;
import com.bantanger.domain.message.verify.mapper.VerifyRecordMapper;
import com.bantanger.domain.message.verify.query.VerifyRecordQuery;
import com.bantanger.domain.message.verify.repository.VerifyRecordRepository;
import com.bantanger.domain.message.verify.updater.VerifyRecordUpdater;
import com.bantanger.domain.message.verify.vo.VerifyRecordVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class VerifyRecordServiceImpl implements IVerifyRecordService {
   private final VerifyRecordRepository verifyRecordRepository;

   /**
    * createImpl
    */
   @Override
   public Long createVerifyRecord(VerifyRecordCreator creator) {
      Optional<VerifyRecord> verifyRecord = EntityOperations.doCreate(verifyRecordRepository)
      .create(() -> VerifyRecordMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return verifyRecord.isPresent() ? verifyRecord.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateVerifyRecord(VerifyRecordUpdater updater) {
      EntityOperations.doUpdate(verifyRecordRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateVerifyRecord(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validVerifyRecord(Long id) {
      EntityOperations.doUpdate(verifyRecordRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidVerifyRecord(Long id) {
      EntityOperations.doUpdate(verifyRecordRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public VerifyRecordVO findById(Long id) {
      Optional<VerifyRecord> verifyRecord =  verifyRecordRepository.findById(id);
      return new VerifyRecordVO(verifyRecord.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<VerifyRecordVO> findByPage(PageRequestWrapper<VerifyRecordQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<VerifyRecord> page = verifyRecordRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(VerifyRecordVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
