// --- Auto Generated by BanTanger ---
package com.bantanger.domain.template.selectdict.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.template.selectdict.creator.SelectDictCreator;
import com.bantanger.domain.template.selectdict.query.SelectDictQuery;
import com.bantanger.domain.template.selectdict.updater.SelectDictUpdater;
import com.bantanger.domain.template.selectdict.vo.SelectDictVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface ISelectDictService {
   /**
    * create
    */
   Long createSelectDict(SelectDictCreator creator);

   /**
    * update
    */
   void updateSelectDict(SelectDictUpdater updater);

   /**
    * valid
    */
   void validSelectDict(Long id);

   /**
    * invalid
    */
   void invalidSelectDict(Long id);

   /**
    * findById
    */
   SelectDictVO findById(Long id);

   /**
    * findByPage
    */
   Page<SelectDictVO> findByPage(PageRequestWrapper<SelectDictQuery> query);
}
