// --- Auto Generated by BanTanger ---
package com.bantanger.api.trade.orderitem.request;

import com.bantanger.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.math.BigDecimal;

@Schema
public class OrderItemUpdateRequest implements Request {
   @Schema(
         title = "订单ID"
   )
   private Long orderId;

   @Schema(
         title = "唯一流水号"
   )
   private Long flowId;

   @Schema(
         title = "真实金额"
   )
   private BigDecimal realAmount;

   @Schema(
         title = "计量数量"
   )
   private Integer itemCount;

   @Schema(
         title = "商品 sku 编号"
   )
   private String skuId;

   @Schema(
         title = "商品计量单位"
   )
   private String itemUnit;

   @Schema(
         title = "商品名称"
   )
   private String goodsName;

   @Schema(
         title = "费用描述"
   )
   private String feeRemark;

   private Long id;

   public Long getOrderId() {
      return orderId;
   }

   public void setOrderId(Long orderId) {
      this.orderId = orderId;
   }

   public Long getFlowId() {
      return flowId;
   }

   public void setFlowId(Long flowId) {
      this.flowId = flowId;
   }

   public BigDecimal getRealAmount() {
      return realAmount;
   }

   public void setRealAmount(BigDecimal realAmount) {
      this.realAmount = realAmount;
   }

   public Integer getItemCount() {
      return itemCount;
   }

   public void setItemCount(Integer itemCount) {
      this.itemCount = itemCount;
   }

   public String getSkuId() {
      return skuId;
   }

   public void setSkuId(String skuId) {
      this.skuId = skuId;
   }

   public String getItemUnit() {
      return itemUnit;
   }

   public void setItemUnit(String itemUnit) {
      this.itemUnit = itemUnit;
   }

   public String getGoodsName() {
      return goodsName;
   }

   public void setGoodsName(String goodsName) {
      this.goodsName = goodsName;
   }

   public String getFeeRemark() {
      return feeRemark;
   }

   public void setFeeRemark(String feeRemark) {
      this.feeRemark = feeRemark;
   }

   public Long getId() {
      return id;
   }

   public void setId(long id) {
      this.id = id;
   }
}
