// --- Auto Generated by BanTanger ---
package com.bantanger.domain.template.objecttemplate.repository;

import com.bantanger.domain.template.objecttemplate.ObjectTemplate;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface ObjectTemplateRepository extends BaseRepository<ObjectTemplate, Long> {
}
