// --- Auto Generated by BanTanger ---
package com.bantanger.domain.template.objecttemplate.repository;

import com.bantanger.domain.template.objecttemplate.TemplateItemRel;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface TemplateItemRelRepository extends BaseRepository<TemplateItemRel, Long> {
}
