// --- Auto Generated by BanTanger ---
package com.bantanger.domain.template.objecttemplate.repository;

import com.bantanger.domain.template.objecttemplate.TemplateCategory;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface TemplateCategoryRepository extends BaseRepository<TemplateCategory, Long> {
}
