// --- Auto Generated by BanTanger ---
package com.bantanger.api.asset.request;

import com.bantanger.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;

@Schema
public class AssetUpdateRequest implements Request {
   @Schema(
         title = "仓库编码ID"
   )
   private Long warehouseId;

   @Schema(
         title = "资产名称"
   )
   private String name;

   @Schema(
         title = "资产唯一编码"
   )
   private String uniqueCode;

   @Schema(
         title = "资产skuId"
   )
   private Long skuId;

   private Long id;

   public Long getWarehouseId() {
      return warehouseId;
   }

   public void setWarehouseId(Long warehouseId) {
      this.warehouseId = warehouseId;
   }

   public String getName() {
      return name;
   }

   public void setName(String name) {
      this.name = name;
   }

   public String getUniqueCode() {
      return uniqueCode;
   }

   public void setUniqueCode(String uniqueCode) {
      this.uniqueCode = uniqueCode;
   }

   public Long getSkuId() {
      return skuId;
   }

   public void setSkuId(Long skuId) {
      this.skuId = skuId;
   }

   public Long getId() {
      return id;
   }

   public void setId(long id) {
      this.id = id;
   }
}
