// --- Auto Generated by BanTanger ---
package com.bantanger.api.message.record.request;

import com.bantanger.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;

@Schema
public class MessageRecordUpdateRequest implements Request {
   @Schema(
         title = "模板编码"
   )
   private String templateCode;

   @Schema(
         title = "消息内容"
   )
   private String messageContent;

   @Schema(
         title = "执行参数"
   )
   private String params;

   @Schema(
         title = "消息类型"
   )
   private String msgType;

   @Schema(
         title = "通知类型"
   )
   private String notifyType;

   private Long id;

   public String getTemplateCode() {
      return templateCode;
   }

   public void setTemplateCode(String templateCode) {
      this.templateCode = templateCode;
   }

   public String getMessageContent() {
      return messageContent;
   }

   public void setMessageContent(String messageContent) {
      this.messageContent = messageContent;
   }

   public String getParams() {
      return params;
   }

   public void setParams(String params) {
      this.params = params;
   }

   public String getMsgType() {
      return msgType;
   }

   public void setMsgType(String msgType) {
      this.msgType = msgType;
   }

   public String getNotifyType() {
      return notifyType;
   }

   public void setNotifyType(String notifyType) {
      this.notifyType = notifyType;
   }

   public Long getId() {
      return id;
   }

   public void setId(long id) {
      this.id = id;
   }
}
