// --- Auto Generated by BanTanger ---
package com.bantanger.api.user.response;

import com.bantanger.common.enums.ValidStatus;
import com.bantanger.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.String;

@Schema
public class UserBaseResponse extends AbstractJpaResponse {
   @Schema(
         title = "uuid防重"
   )
   private String uuid;

   @Schema(
         title = "手机号"
   )
   private String phone;

   @Schema(
         title = "validStatus"
   )
   private ValidStatus validStatus;

   public String getUuid() {
      return uuid;
   }

   public void setUuid(String uuid) {
      this.uuid = uuid;
   }

   public String getPhone() {
      return phone;
   }

   public void setPhone(String phone) {
      this.phone = phone;
   }

   public ValidStatus getValidStatus() {
      return validStatus;
   }

   public void setValidStatus(ValidStatus validStatus) {
      this.validStatus = validStatus;
   }
}
