// --- Auto Generated by BanTanger ---
package com.bantanger.api.user.response;

import com.bantanger.common.enums.ValidStatus;
import com.bantanger.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;

@Schema
public class UserAccountResponse extends AbstractJpaResponse {
   @Schema(
         title = "用户ID"
   )
   private Long userId;

   @Schema(
         title = "账号ID"
   )
   private String accountNo;

   @Schema(
         title = "账号类别"
   )
   private Integer accountType;

   @Schema(
         title = "validStatus"
   )
   private ValidStatus validStatus;

   public Long getUserId() {
      return userId;
   }

   public void setUserId(Long userId) {
      this.userId = userId;
   }

   public String getAccountNo() {
      return accountNo;
   }

   public void setAccountNo(String accountNo) {
      this.accountNo = accountNo;
   }

   public Integer getAccountType() {
      return accountType;
   }

   public void setAccountType(Integer accountType) {
      this.accountType = accountType;
   }

   public ValidStatus getValidStatus() {
      return validStatus;
   }

   public void setValidStatus(ValidStatus validStatus) {
      this.validStatus = validStatus;
   }
}
