// --- Auto Generated by BanTanger ---
package com.bantanger.domain.message.record.service;

import com.bantanger.common.constants.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.message.record.MessageRecord;
import com.bantanger.domain.message.record.creator.MessageRecordCreator;
import com.bantanger.domain.message.record.mapper.MessageRecordMapper;
import com.bantanger.domain.message.record.query.MessageRecordQuery;
import com.bantanger.domain.message.record.repository.MessageRecordRepository;
import com.bantanger.domain.message.record.updater.MessageRecordUpdater;
import com.bantanger.domain.message.record.vo.MessageRecordVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class MessageRecordServiceImpl implements IMessageRecordService {
   private final MessageRecordRepository messageRecordRepository;

   /**
    * createImpl
    */
   @Override
   public Long createMessageRecord(MessageRecordCreator creator) {
      Optional<MessageRecord> messageRecord = EntityOperations.doCreate(messageRecordRepository)
      .create(() -> MessageRecordMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return messageRecord.isPresent() ? messageRecord.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateMessageRecord(MessageRecordUpdater updater) {
      EntityOperations.doUpdate(messageRecordRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateMessageRecord(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validMessageRecord(Long id) {
      EntityOperations.doUpdate(messageRecordRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidMessageRecord(Long id) {
      EntityOperations.doUpdate(messageRecordRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public MessageRecordVO findById(Long id) {
      Optional<MessageRecord> messageRecord =  messageRecordRepository.findById(id);
      return new MessageRecordVO(messageRecord.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<MessageRecordVO> findByPage(PageRequestWrapper<MessageRecordQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<MessageRecord> page = messageRecordRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(MessageRecordVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
