// --- Auto Generated by BanTanger ---
package com.bantanger.domain.stock.seat.repository;

import com.bantanger.domain.stock.seat.SeatStockDetail;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface SeatStockDetailRepository extends BaseRepository<SeatStockDetail, Long> {
}
