// --- Auto Generated by BanTanger ---
package com.bantanger.domain.stock.seat.repository;

import com.bantanger.domain.stock.seat.SeatStock;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface SeatStockRepository extends BaseRepository<SeatStock, Long> {
}
