// --- Auto Generated by BanTanger ---
package com.bantanger.api.template.selectdict.request;

import com.bantanger.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class SelectDictQueryRequest implements Request {
}
