// --- Auto Generated by BanTanger ---
package com.bantanger.api.template.selectdict.request;

import com.bantanger.common.model.CodeValue;
import com.bantanger.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.String;
import java.util.List;

@Schema
public class SelectDictCreateRequest implements Request {
   @Schema(
         title = "字典编码"
   )
   private String code;

   @Schema(
         title = "字典名称"
   )
   private String name;

   @Schema(
         title = "字典描述"
   )
   private String desc;

   @Schema(
         title = "字典类型"
   )
   private Integer dictType;

   @Schema(
         title = "HTTP接口地址"
   )
   private String httpUrl;

   @Schema(
         title = "选择值列表"
   )
   private List<CodeValue> selectValues;

   public String getCode() {
      return code;
   }

   public void setCode(String code) {
      this.code = code;
   }

   public String getName() {
      return name;
   }

   public void setName(String name) {
      this.name = name;
   }

   public String getDesc() {
      return desc;
   }

   public void setDesc(String desc) {
      this.desc = desc;
   }

   public Integer getDictType() {
      return dictType;
   }

   public void setDictType(Integer dictType) {
      this.dictType = dictType;
   }

   public String getHttpUrl() {
      return httpUrl;
   }

   public void setHttpUrl(String httpUrl) {
      this.httpUrl = httpUrl;
   }

   public List<CodeValue> getSelectValues() {
      return selectValues;
   }

   public void setSelectValues(List<CodeValue> selectValues) {
      this.selectValues = selectValues;
   }
}
