// --- Auto Generated by BanTanger ---
package com.bantanger.domain.trade.order.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.trade.order.creator.OrderBaseCreator;
import com.bantanger.domain.trade.order.query.OrderBaseQuery;
import com.bantanger.domain.trade.order.updater.OrderBaseUpdater;
import com.bantanger.domain.trade.order.vo.OrderBaseVO;
import org.springframework.data.domain.Page;

public interface IOrderBaseService {

    /**
     * create
     */
    Long createOrderBase(OrderBaseCreator creator);

    /**
     * update
     */
    void updateOrderBase(OrderBaseUpdater updater);

    /**
     * valid
     */
    void validOrderBase(Long id);

    /**
     * invalid
     */
    void invalidOrderBase(Long id);

    /**
     * findById
     */
    OrderBaseVO findById(Long id);

    /**
     * findByPage
     */
    Page<OrderBaseVO> findByPage(PageRequestWrapper<OrderBaseQuery> query);
}
