// --- Auto Generated by BanTanger ---
package com.bantanger.domain.trade.order.service;

import com.bantanger.common.constants.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.trade.order.OrderBase;
import com.bantanger.domain.trade.order.creator.OrderBaseCreator;
import com.bantanger.domain.trade.order.mapper.OrderBaseEntityMapper;
import com.bantanger.domain.trade.order.query.OrderBaseQuery;
import com.bantanger.domain.trade.order.repository.OrderBaseRepository;
import com.bantanger.domain.trade.order.updater.OrderBaseUpdater;
import com.bantanger.domain.trade.order.vo.OrderBaseVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class OrderBaseServiceImpl implements IOrderBaseService {
   private final OrderBaseRepository orderBaseRepository;

   /**
    * createImpl
    */
   @Override
   public Long createOrderBase(OrderBaseCreator creator) {
      Optional<OrderBase> orderBase = EntityOperations.doCreate(orderBaseRepository)
      .create(() -> OrderBaseEntityMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return orderBase.isPresent() ? orderBase.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateOrderBase(OrderBaseUpdater updater) {
      EntityOperations.doUpdate(orderBaseRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateOrderBase(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validOrderBase(Long id) {
      EntityOperations.doUpdate(orderBaseRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidOrderBase(Long id) {
      EntityOperations.doUpdate(orderBaseRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public OrderBaseVO findById(Long id) {
      Optional<OrderBase> orderBase =  orderBaseRepository.findById(id);
      return new OrderBaseVO(orderBase.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<OrderBaseVO> findByPage(PageRequestWrapper<OrderBaseQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<OrderBase> page = orderBaseRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(OrderBaseVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
