// --- Auto Generated by BanTanger ---
package com.bantanger.domain.admin.repository;

import com.bantanger.domain.admin.AdminUserRole;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface AdminUserRoleRepository extends BaseRepository<AdminUserRole, Long> {
}
