// --- Auto Generated by BanTanger ---
package com.bantanger.domain.admin.repository;

import com.bantanger.domain.admin.AdminUserPlatform;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface AdminUserPlatformRepository extends BaseRepository<AdminUserPlatform, Long> {
}
