// --- Auto Generated by BanTanger ---
package com.bantanger.domain.admin.repository;

import com.bantanger.domain.admin.AdminUser;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface AdminUserRepository extends BaseRepository<AdminUser, Long> {
}
