// --- Auto Generated by BanTanger ---
package com.bantanger.api.template.objecttemplate.request;

import com.bantanger.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class TemplateCategoryQueryRequest implements Request {
}
