server:
  port: 8091

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/system-center?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      max-lifetime: 600000
    tomcat:
      test-on-borrow: true
      validation-query: SELECT  1
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        generate_statistics: false
        jdbc:
          batch_size: 1000
        order_inserts: true
        hbm2ddl:
          auto: update

# Redis【如需使用请打开】
#redis:
#  sdk:
#    config:
#      host: 127.0.0.1
#      port: 6379
#      pool-size: 10
#      min-idle-size: 5
#      idle-timeout: 30000
#      connect-timeout: 5000
#      retry-attempts: 3
#      retry-interval: 1000
#      ping-interval: 60000
#      keep-alive: true

# MyBatis 配置【如需使用记得打开】
#mybatis:
#  mapper-locations: classpath:/mybatis/mapper/*.xml
#  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 日志
logging:
  level:
    '[net.ttddyy.dsproxy.listener]': debug
    root: info
  config: classpath:logback-spring.xml

bt:
  message:
    verifyLength: 6
    validTime: 5
    sendInterval: 1
    sendMaxTimes: 10