server:
  port: 8091

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  main: # 全局懒加载配置
    lazy-initialization: true  #默认false 关闭
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/system-center?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      max-lifetime: 600000
    tomcat:
      test-on-borrow: true
      validation-query: SELECT  1
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        generate_statistics: false
        jdbc:
          batch_size: 1000
        order_inserts: true
        hbm2ddl:
          auto: update

rocketmq:
  enhance:
    # 启动隔离，用于激活配置类EnvironmentIsolationConfig
    # 启动后会自动在topic上拼接激活的配置文件，达到自动隔离的效果
    enabledIsolation: true
    # 隔离环境名称，拼接到topic后，topic_dev，默认空字符串
    environment: dev
  consumer:
    group: test_consumer_group
    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
    pull-batch-size: 10
  name-server: 127.0.0.1:9876
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: test_producer_group
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 10000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false

# redisson配置
redisson:
  # 如果该值为false，系统将不会创建RedissionClient的bean。
  enabled: true
  # mode的可用值为，single/cluster/sentinel/master-slave
  mode: single
  # single: 单机模式
  #   address: redis://localhost:6379
  # cluster: 集群模式
  #   每个节点逗号分隔，同时每个节点前必须以redis://开头。
  #   address: redis://localhost:6379,redis://localhost:6378,...
  # sentinel:
  #   每个节点逗号分隔，同时每个节点前必须以redis://开头。
  #   address: redis://localhost:6379,redis://localhost:6378,...
  # master-slave:
  #   每个节点逗号分隔，第一个为主节点，其余为从节点。同时每个节点前必须以redis://开头。
  #   address: redis://localhost:6379,redis://localhost:6378,...
  address: redis://127.0.0.1:6001
  # redis 密码，空可以不填。
  password:
  database: 0

# MyBatis 配置【如需使用记得打开】
#mybatis:
#  mapper-locations: classpath:/mybatis/mapper/*.xml
#  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 日志
logging:
  level:
    '[net.ttddyy.dsproxy.listener]': info
    root: info
    RocketmqClient: ERROR
    io:
      netty: ERROR
  config: classpath:logback-spring.xml

bt:
  message:
    verifyLength: 6
    validTime: 5
    sendInterval: 1
    sendMaxTimes: 10