// --- Auto Generated by BanTanger ---
package com.bantanger.domain.asset.lifecycle.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.asset.lifecycle.creator.AssetLifecycleCreator;
import com.bantanger.domain.asset.lifecycle.query.AssetLifecycleQuery;
import com.bantanger.domain.asset.lifecycle.updater.AssetLifecycleUpdater;
import com.bantanger.domain.asset.lifecycle.vo.AssetLifecycleVO;
import java.lang.Long;
import java.util.List;
import org.springframework.data.domain.Page;

public interface IAssetLifecycleService {

   /**
    * 批量保存
    * @param batchNo 批号(自动生成批号，非展示批号)
    * @param creatorList
    */
   void batchCreateLifecycle(String batchNo, List<AssetLifecycleCreator> creatorList);

   /**
    * create
    */
   Long createAssetLifecycle(AssetLifecycleCreator creator);

   /**
    * update
    */
   void updateAssetLifecycle(AssetLifecycleUpdater updater);

   /**
    * valid
    */
   void validAssetLifecycle(Long id);

   /**
    * invalid
    */
   void invalidAssetLifecycle(Long id);

   /**
    * findById
    */
   AssetLifecycleVO findById(Long id);

   /**
    * findByPage
    */
   Page<AssetLifecycleVO> findByPage(PageRequestWrapper<AssetLifecycleQuery> query);
}
