// --- Auto Generated by BanTanger ---
package com.bantanger.domain.trade.reviserecord.service;

import com.bantanger.common.constants.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.trade.reviserecord.ReviseRecord;
import com.bantanger.domain.trade.reviserecord.creator.ReviseRecordCreator;
import com.bantanger.domain.trade.reviserecord.mapper.ReviseRecordMapper;
import com.bantanger.domain.trade.reviserecord.query.ReviseRecordQuery;
import com.bantanger.domain.trade.reviserecord.repository.ReviseRecordRepository;
import com.bantanger.domain.trade.reviserecord.updater.ReviseRecordUpdater;
import com.bantanger.domain.trade.reviserecord.vo.ReviseRecordVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class ReviseRecordServiceImpl implements IReviseRecordService {
   private final ReviseRecordRepository reviseRecordRepository;

   /**
    * createImpl
    */
   @Override
   public Long createReviseRecord(ReviseRecordCreator creator) {
      Optional<ReviseRecord> reviseRecord = EntityOperations.doCreate(reviseRecordRepository)
      .create(() -> ReviseRecordMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return reviseRecord.isPresent() ? reviseRecord.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateReviseRecord(ReviseRecordUpdater updater) {
      EntityOperations.doUpdate(reviseRecordRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateReviseRecord(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validReviseRecord(Long id) {
      EntityOperations.doUpdate(reviseRecordRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidReviseRecord(Long id) {
      EntityOperations.doUpdate(reviseRecordRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public ReviseRecordVO findById(Long id) {
      Optional<ReviseRecord> reviseRecord =  reviseRecordRepository.findById(id);
      return new ReviseRecordVO(reviseRecord.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<ReviseRecordVO> findByPage(PageRequestWrapper<ReviseRecordQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<ReviseRecord> page = reviseRecordRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(ReviseRecordVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
