// --- Auto Generated by BanTanger ---
package com.bantanger.domain.trade.orderlifecycle.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.trade.orderlifecycle.creator.OrderLifecycleCreator;
import com.bantanger.domain.trade.orderlifecycle.query.OrderLifecycleQuery;
import com.bantanger.domain.trade.orderlifecycle.updater.OrderLifecycleUpdater;
import com.bantanger.domain.trade.orderlifecycle.vo.OrderLifecycleVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IOrderLifecycleService {
   /**
    * create
    */
   Long createOrderLifecycle(OrderLifecycleCreator creator);

   /**
    * update
    */
   void updateOrderLifecycle(OrderLifecycleUpdater updater);

   /**
    * valid
    */
   void validOrderLifecycle(Long id);

   /**
    * invalid
    */
   void invalidOrderLifecycle(Long id);

   /**
    * findById
    */
   OrderLifecycleVO findById(Long id);

   /**
    * findByPage
    */
   Page<OrderLifecycleVO> findByPage(PageRequestWrapper<OrderLifecycleQuery> query);
}
