// --- Auto Generated by BanTanger ---
package com.bantanger.domain.trade.reviserecord.repository;

import com.bantanger.domain.trade.reviserecord.ReviseRecord;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface ReviseRecordRepository extends BaseRepository<ReviseRecord, Long> {
}
