// --- Auto Generated by BanTanger ---
package com.bantanger.domain.asset.asset.service;

import com.bantanger.common.constants.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.asset.asset.Asset;
import com.bantanger.domain.asset.asset.creator.AssetCreator;
import com.bantanger.domain.asset.asset.mapper.AssetMapper;
import com.bantanger.domain.asset.asset.query.AssetQuery;
import com.bantanger.domain.asset.asset.repository.AssetRepository;
import com.bantanger.domain.asset.asset.updater.AssetUpdater;
import com.bantanger.domain.asset.asset.vo.AssetVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class AssetServiceImpl implements IAssetService {
   private final AssetRepository assetRepository;

   /**
    * createImpl
    */
   @Override
   public Long createAsset(AssetCreator creator) {
      Optional<Asset> asset = EntityOperations.doCreate(assetRepository)
      .create(() -> AssetMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return asset.isPresent() ? asset.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateAsset(AssetUpdater updater) {
      EntityOperations.doUpdate(assetRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateAsset(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validAsset(Long id) {
      EntityOperations.doUpdate(assetRepository)
      .loadById(id)
      .update(e -> {})
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidAsset(Long id) {
      EntityOperations.doUpdate(assetRepository)
      .loadById(id)
      .update(e -> {})
      .execute();
   }

   /**
    * findById
    */
   @Override
   public AssetVO findById(Long id) {
      Optional<Asset> asset =  assetRepository.findById(id);
      return new AssetVO(asset.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<AssetVO> findByPage(PageRequestWrapper<AssetQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<Asset> page = assetRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(AssetVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
