// --- Auto Generated by BanTanger ---
package com.bantanger.domain.asset.asset.service;

import com.bantanger.common.enums.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.asset.asset.Asset;
import com.bantanger.domain.asset.asset.query.AssetQuery;
import com.bantanger.domain.asset.asset.repository.AssetRepository;
import com.bantanger.domain.asset.asset.vo.AssetVO;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class AssetServiceImpl implements IAssetService {
   private final AssetRepository assetRepository;

   /**
    * findById
    */
   @Override
   public AssetVO findById(Long id) {
      Optional<Asset> asset =  assetRepository.findById(id);
      return new AssetVO(asset.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<AssetVO> findByPage(PageRequestWrapper<AssetQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<Asset> page = assetRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(AssetVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
