// --- Auto Generated by BanTanger ---
package com.bantanger.domain.asset.asset.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.asset.asset.creator.AssetCreator;
import com.bantanger.domain.asset.asset.query.AssetQuery;
import com.bantanger.domain.asset.asset.updater.AssetUpdater;
import com.bantanger.domain.asset.asset.vo.AssetVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IAssetService {

   /**
    * findById
    */
   AssetVO findById(Long id);

   /**
    * findByPage
    */
   Page<AssetVO> findByPage(PageRequestWrapper<AssetQuery> query);
}
