// --- Auto Generated by BanTanger ---
package com.bantanger.codegen.repository;

import com.bantanger.codegen.Student;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface StudentRepository extends BaseRepository<Student, Long> {
}
