// --- Auto Generated by BanTanger ---
package com.bantanger.codegen.mapper;

import com.bantanger.codegen.Student;
import com.bantanger.codegen.creator.StudentCreator;
import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
      uses = {
            GenericEnumMapper.class,
            DateMapper.class
      }
)
public interface StudentEntityMapper {
   StudentEntityMapper INSTANCE = Mappers.getMapper(StudentEntityMapper.class);

   Student dtoToEntity(StudentCreator dto);
}
