// --- Auto Generated by BanTanger ---
package com.bantanger.codegen.mapper;

import com.bantanger.codegen.Student;
import com.bantanger.codegen.creator.StudentCreator;
import com.bantanger.codegen.query.StudentQuery;
import com.bantanger.codegen.request.StudentCreateRequest;
import com.bantanger.codegen.request.StudentQueryRequest;
import com.bantanger.codegen.request.StudentUpdateRequest;
import com.bantanger.codegen.response.StudentResponse;
import com.bantanger.codegen.updater.StudentUpdater;
import com.bantanger.codegen.vo.StudentVO;
import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
      uses = {
            GenericEnumMapper.class,
            DateMapper.class
      }
)
public interface StudentMapper {
   StudentMapper INSTANCE = Mappers.getMapper(StudentMapper.class);

   Student dtoToEntity(StudentCreator dto);

   StudentUpdater request2Updater(StudentUpdateRequest request);

   StudentCreator request2Dto(StudentCreateRequest request);

   StudentQuery request2Query(StudentQueryRequest request);

   StudentResponse vo2Response(StudentVO vo);

   default StudentResponse vo2CustomResponse(StudentVO vo) {
      StudentResponse response = vo2Response(vo);
      return response;
   }
}
