// --- Auto Generated by BanTanger ---
package com.bantanger.domain.asset.record.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.asset.record.creator.AssetInOutRecordCreator;
import com.bantanger.domain.asset.record.query.AssetInOutRecordQuery;
import com.bantanger.domain.asset.record.updater.AssetInOutRecordUpdater;
import com.bantanger.domain.asset.record.vo.AssetInOutRecordVO;
import java.lang.Long;
import java.util.List;
import org.springframework.data.domain.Page;

public interface IAssetInOutRecordService {
   /**
    * create
    */
   Long createAssetInOutRecord(List<String> uniqueCodes, AssetInOutRecordCreator creator);

   /**
    * findById
    */
   AssetInOutRecordVO findById(Long id);

   /**
    * findByPage
    */
   Page<AssetInOutRecordVO> findByPage(PageRequestWrapper<AssetInOutRecordQuery> query);
}
