// --- Auto Generated by BanTanger ---
package com.bantanger.domain.message.template.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.message.template.creator.MessageTemplateCreator;
import com.bantanger.domain.message.template.query.MessageTemplateQuery;
import com.bantanger.domain.message.template.updater.MessageTemplateUpdater;
import com.bantanger.domain.message.template.vo.MessageTemplateVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IMessageTemplateService {
   /**
    * create
    */
   Long createMessageTemplate(MessageTemplateCreator creator);

   /**
    * update
    */
   void updateMessageTemplate(MessageTemplateUpdater updater);

   /**
    * valid
    */
   void validMessageTemplate(Long id);

   /**
    * invalid
    */
   void invalidMessageTemplate(Long id);

   /**
    * findById
    */
   MessageTemplateVO findById(Long id);

   /**
    * findByPage
    */
   Page<MessageTemplateVO> findByPage(PageRequestWrapper<MessageTemplateQuery> query);
}
