// --- Auto Generated by BanTanger ---
package com.bantanger.domain.permission.role.repository;

import com.bantanger.domain.permission.role.Role;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface RoleRepository extends BaseRepository<Role, Long> {
}
