// --- Auto Generated by BanTanger ---
package com.bantanger.api.stock.seat.response;

import com.bantanger.common.enums.ValidStatus;
import com.bantanger.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.String;

@Schema
public class SeatStockResponse extends AbstractJpaResponse {
   @Schema(
         title = "场次唯一标识"
   )
   private String showId;

   @Schema(
         title = "总库存数"
   )
   private Integer totalNum;

   @Schema(
         title = "已售数量"
   )
   private Integer soldNum;

   @Schema(
         title = "validStatus"
   )
   private ValidStatus validStatus;

   public String getShowId() {
      return showId;
   }

   public void setShowId(String showId) {
      this.showId = showId;
   }

   public Integer getTotalNum() {
      return totalNum;
   }

   public void setTotalNum(Integer totalNum) {
      this.totalNum = totalNum;
   }

   public Integer getSoldNum() {
      return soldNum;
   }

   public void setSoldNum(Integer soldNum) {
      this.soldNum = soldNum;
   }

   public ValidStatus getValidStatus() {
      return validStatus;
   }

   public void setValidStatus(ValidStatus validStatus) {
      this.validStatus = validStatus;
   }
}
