// --- Auto Generated by BanTanger ---
package com.bantanger.api.stock.seat.response;

import com.bantanger.common.enums.ValidStatus;
import com.bantanger.common.model.AbstractJpaResponse;
import com.bantanger.common.model.CodeValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.time.Instant;
import java.util.List;

@Schema
public class SeatStockDetailResponse extends AbstractJpaResponse {
   @Schema(
         title = "座位库存ID"
   )
   private Long stockId;

   @Schema(
         title = "用户ID"
   )
   private Long userId;

   @Schema(
         title = "场次唯一标识"
   )
   private String showId;

   @Schema(
         title = "在线座位唯一标识"
   )
   private String seatNo;

   @Schema(
         title = "在线座位库存状态"
   )
   private Integer seatStockStatus;

   @Schema(
         title = "座位类型"
   )
   private Integer seatType;

   @Schema(
         title = "座位信息"
   )
   private String seatInfo;

   @Schema(
         title = "扩展信息"
   )
   private List<CodeValue> extraInfo;

   @Schema(
         title = "预占库存时间"
   )
   private Instant lockTime;

   @Schema(
         title = "释放库存时间"
   )
   private Instant expireTime;

   @Schema(
         title = "核销库存时间"
   )
   private Instant submitTime;

   @Schema(
         title = "validStatus"
   )
   private ValidStatus validStatus;

   public Long getStockId() {
      return stockId;
   }

   public void setStockId(Long stockId) {
      this.stockId = stockId;
   }

   public Long getUserId() {
      return userId;
   }

   public void setUserId(Long userId) {
      this.userId = userId;
   }

   public String getShowId() {
      return showId;
   }

   public void setShowId(String showId) {
      this.showId = showId;
   }

   public String getSeatNo() {
      return seatNo;
   }

   public void setSeatNo(String seatNo) {
      this.seatNo = seatNo;
   }

   public Integer getSeatStockStatus() {
      return seatStockStatus;
   }

   public void setSeatStockStatus(Integer seatStockStatus) {
      this.seatStockStatus = seatStockStatus;
   }

   public Integer getSeatType() {
      return seatType;
   }

   public void setSeatType(Integer seatType) {
      this.seatType = seatType;
   }

   public String getSeatInfo() {
      return seatInfo;
   }

   public void setSeatInfo(String seatInfo) {
      this.seatInfo = seatInfo;
   }

   public List<CodeValue> getExtraInfo() {
      return extraInfo;
   }

   public void setExtraInfo(List<CodeValue> extraInfo) {
      this.extraInfo = extraInfo;
   }

   public Instant getLockTime() {
      return lockTime;
   }

   public void setLockTime(Instant lockTime) {
      this.lockTime = lockTime;
   }

   public Instant getExpireTime() {
      return expireTime;
   }

   public void setExpireTime(Instant expireTime) {
      this.expireTime = expireTime;
   }

   public Instant getSubmitTime() {
      return submitTime;
   }

   public void setSubmitTime(Instant submitTime) {
      this.submitTime = submitTime;
   }

   public ValidStatus getValidStatus() {
      return validStatus;
   }

   public void setValidStatus(ValidStatus validStatus) {
      this.validStatus = validStatus;
   }
}
