// --- Auto Generated by BanTanger ---
package com.bantanger.domain.trade.order.repository;

import com.bantanger.domain.trade.order.OrderBase;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface OrderBaseRepository extends BaseRepository<OrderBase, Long> {
}
