// --- Auto Generated by BanTanger ---
package com.bantanger.domain.message.record.repository;

import com.bantanger.domain.message.record.MessageRecord;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface MessageRecordRepository extends BaseRepository<MessageRecord, Long> {
}
