// --- Auto Generated by BanTanger ---
package com.bantanger.trigger.asset.controller;

import com.bantanger.api.asset.request.AssetCreateRequest;
import com.bantanger.api.asset.request.AssetQueryRequest;
import com.bantanger.api.asset.request.AssetUpdateRequest;
import com.bantanger.api.asset.response.AssetResponse;
import com.bantanger.common.constants.CodeEnum;
import com.bantanger.common.model.JsonObject;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.common.model.PageResult;
import com.bantanger.domain.asset.asset.creator.AssetCreator;
import com.bantanger.domain.asset.asset.mapper.AssetMapper;
import com.bantanger.domain.asset.asset.query.AssetQuery;
import com.bantanger.domain.asset.asset.service.IAssetService;
import com.bantanger.domain.asset.asset.updater.AssetUpdater;
import com.bantanger.domain.asset.asset.vo.AssetVO;
import java.lang.Long;
import java.lang.String;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Slf4j
@RequestMapping("asset/v1/")
@RequiredArgsConstructor
public class AssetController {
   private final IAssetService assetService;

   /**
    * createRequest
    */
   @PostMapping("createAsset")
   public JsonObject<Long> createAsset(@RequestBody AssetCreateRequest request) {
      AssetCreator creator = AssetMapper.INSTANCE.request2Dto(request);
      return JsonObject.success(assetService.createAsset(creator));
   }

   /**
    * update request
    */
   @PostMapping("updateAsset")
   public JsonObject<String> updateAsset(@RequestBody AssetUpdateRequest request) {
      AssetUpdater updater = AssetMapper.INSTANCE.request2Updater(request);
      assetService.updateAsset(updater);
      return JsonObject.success(CodeEnum.Success.getName());
   }

   /**
    * valid
    */
   @PostMapping("valid/{id}")
   public JsonObject<String> validAsset(@PathVariable Long id) {
      assetService.validAsset(id);
      return JsonObject.success(CodeEnum.Success.getName());
   }

   /**
    * invalid
    */
   @PostMapping("invalid/{id}")
   public JsonObject<String> invalidAsset(@PathVariable Long id) {
      assetService.invalidAsset(id);
      return JsonObject.success(CodeEnum.Success.getName());
   }

   /**
    * findById
    */
   @GetMapping("findById/{id}")
   public JsonObject<AssetResponse> findById(@PathVariable Long id) {
      AssetVO vo = assetService.findById(id);
      AssetResponse response = AssetMapper.INSTANCE.vo2CustomResponse(vo);
      return JsonObject.success(response);
   }

   /**
    * findByPage request
    */
   @PostMapping("findByPage")
   public JsonObject<PageResult<AssetResponse>> findByPage(
         @RequestBody PageRequestWrapper<AssetQueryRequest> request) {
      PageRequestWrapper<AssetQuery> wrapper = new PageRequestWrapper<>();
      wrapper.setBean(AssetMapper.INSTANCE.request2Query(request.getBean()));
      wrapper.setSorts(request.getSorts());
          wrapper.setPageSize(request.getPageSize());
          wrapper.setPage(request.getPage());
      Page<AssetVO> page = assetService.findByPage(wrapper);
      return JsonObject.success(
              PageResult.of(
                  page.getContent().stream()
                      .map(vo -> AssetMapper.INSTANCE.vo2CustomResponse(vo))
                      .collect(Collectors.toList()),
                  page.getTotalElements(),
                  page.getSize(),
                  page.getNumber())
          );
   }
}
