// --- Auto Generated by BanTanger ---
package com.bantanger.domain.trade.orderitem.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.trade.orderitem.creator.OrderItemCreator;
import com.bantanger.domain.trade.orderitem.query.OrderItemQuery;
import com.bantanger.domain.trade.orderitem.updater.OrderItemUpdater;
import com.bantanger.domain.trade.orderitem.vo.OrderItemVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IOrderItemService {
   /**
    * create
    */
   Long createOrderItem(OrderItemCreator creator);

   /**
    * update
    */
   void updateOrderItem(OrderItemUpdater updater);

   /**
    * valid
    */
   void validOrderItem(Long id);

   /**
    * invalid
    */
   void invalidOrderItem(Long id);

   /**
    * findById
    */
   OrderItemVO findById(Long id);

   /**
    * findByPage
    */
   Page<OrderItemVO> findByPage(PageRequestWrapper<OrderItemQuery> query);
}
