// --- Auto Generated by BanTanger ---
package com.bantanger.domain.asset.lifecycle.repository;

import com.bantanger.domain.asset.lifecycle.AssetLifecycle;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface AssetLifecycleRepository extends BaseRepository<AssetLifecycle, Long> {
}
