// --- Auto Generated by BanTanger ---
package com.bantanger.domain.asset.warehouse.service;

import com.bantanger.common.constants.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.asset.warehouse.Warehouse;
import com.bantanger.domain.asset.warehouse.creator.WarehouseCreator;
import com.bantanger.domain.asset.warehouse.mapper.WarehouseMapper;
import com.bantanger.domain.asset.warehouse.query.WarehouseQuery;
import com.bantanger.domain.asset.warehouse.repository.WarehouseRepository;
import com.bantanger.domain.asset.warehouse.updater.WarehouseUpdater;
import com.bantanger.domain.asset.warehouse.vo.WarehouseVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class WarehouseServiceImpl implements IWarehouseService {
   private final WarehouseRepository warehouseRepository;

   /**
    * createImpl
    */
   @Override
   public Long createWarehouse(WarehouseCreator creator) {
      Optional<Warehouse> warehouse = EntityOperations.doCreate(warehouseRepository)
      .create(() -> WarehouseMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return warehouse.isPresent() ? warehouse.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateWarehouse(WarehouseUpdater updater) {
      EntityOperations.doUpdate(warehouseRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateWarehouse(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validWarehouse(Long id) {
      EntityOperations.doUpdate(warehouseRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidWarehouse(Long id) {
      EntityOperations.doUpdate(warehouseRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public WarehouseVO findById(Long id) {
      Optional<Warehouse> warehouse =  warehouseRepository.findById(id);
      return new WarehouseVO(warehouse.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<WarehouseVO> findByPage(PageRequestWrapper<WarehouseQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<Warehouse> page = warehouseRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(WarehouseVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
