// --- Auto Generated by BanTanger ---
package com.bantanger.api.trade.reviserecord.request;

import com.bantanger.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;

@Schema
public class ReviseRecordUpdateRequest implements Request {
   private Long id;

   public Long getId() {
      return id;
   }

   public void setId(long id) {
      this.id = id;
   }
}
