// --- Auto Generated by BanTanger ---
package com.bantanger.domain.asset.record.mapper;

import com.bantanger.api.asset.record.request.AssetInOutRecordCreateRequest;
import com.bantanger.api.asset.record.request.AssetInOutRecordQueryRequest;
import com.bantanger.api.asset.record.request.AssetInOutRecordUpdateRequest;
import com.bantanger.api.asset.record.response.AssetInOutRecordResponse;
import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.domain.CustomMapper;
import com.bantanger.domain.asset.record.AssetInOutRecord;
import com.bantanger.domain.asset.record.creator.AssetInOutRecordCreator;
import com.bantanger.domain.asset.record.query.AssetInOutRecordQuery;
import com.bantanger.domain.asset.record.updater.AssetInOutRecordUpdater;
import com.bantanger.domain.asset.record.vo.AssetInOutRecordVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class,
        CustomMapper.class
    }
)
public interface AssetInOutRecordMapper {

    AssetInOutRecordMapper INSTANCE = Mappers.getMapper(AssetInOutRecordMapper.class);

    AssetInOutRecord dtoToEntity(AssetInOutRecordCreator dto);

    AssetInOutRecordUpdater request2Updater(AssetInOutRecordUpdateRequest request);

    AssetInOutRecordCreator request2Dto(AssetInOutRecordCreateRequest request);

    AssetInOutRecordQuery request2Query(AssetInOutRecordQueryRequest request);

    AssetInOutRecordResponse vo2Response(AssetInOutRecordVO vo);

    default AssetInOutRecordResponse vo2CustomResponse(AssetInOutRecordVO vo) {
        AssetInOutRecordResponse response = vo2Response(vo);
        return response;
    }
}
