// --- Auto Generated by BanTanger ---
package com.bantanger.api.trade.order.request;

import com.bantanger.common.model.Request;
import com.bantanger.domain.CodeValue;
import com.bantanger.domain.user.AccountType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.math.BigDecimal;
import java.util.List;

@Schema
public class OrderBaseUpdateRequest implements Request {
   @Schema(
         title = "订单金额"
   )
   private BigDecimal totalAmount;

   @Schema(
         title = "账号类型: 1-个人, 2-企业"
   )
   private AccountType accountType;

   @Schema(
         title = "待支付金额"
   )
   private BigDecimal waitPay;

   @Schema(
         title = "订单附加信息"
   )
   private List<CodeValue> attrs;

   private Long id;

   public BigDecimal getTotalAmount() {
      return totalAmount;
   }

   public void setTotalAmount(BigDecimal totalAmount) {
      this.totalAmount = totalAmount;
   }

   public AccountType getAccountType() {
      return accountType;
   }

   public void setAccountType(AccountType accountType) {
      this.accountType = accountType;
   }

   public BigDecimal getWaitPay() {
      return waitPay;
   }

   public void setWaitPay(BigDecimal waitPay) {
      this.waitPay = waitPay;
   }

   public List<CodeValue> getAttrs() {
      return attrs;
   }

   public void setAttrs(List<CodeValue> attrs) {
      this.attrs = attrs;
   }

   public Long getId() {
      return id;
   }

   public void setId(long id) {
      this.id = id;
   }
}
