// --- Auto Generated by BanTanger ---
package com.bantanger.domain.permission.platform.repository;

import com.bantanger.domain.permission.platform.Platform;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface PlatformRepository extends BaseRepository<Platform, Long> {
}
