// --- Auto Generated by BanTanger ---
package com.bantanger.domain.asset.asset.repository;

import com.bantanger.domain.asset.asset.Asset;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface AssetRepository extends BaseRepository<Asset, Long> {
}
