// --- Auto Generated by BanTanger ---
package com.bantanger.domain.user.repository;

import com.bantanger.domain.user.UserAccount;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface UserAccountRepository extends BaseRepository<UserAccount, Long> {
}
