// --- Auto Generated by BanTanger ---
package com.bantanger.domain.user.repository;

import com.bantanger.domain.user.UserBase;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface UserBaseRepository extends BaseRepository<UserBase, Long> {
}
