// --- Auto Generated by BanTanger ---
package com.bantanger.api.trade.reviserecord.response;

import com.bantanger.common.constants.ValidStatus;
import com.bantanger.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class ReviseRecordResponse extends AbstractJpaResponse {
   @Schema(
         title = "validStatus"
   )
   private ValidStatus validStatus;

   public ValidStatus getValidStatus() {
      return validStatus;
   }

   public void setValidStatus(ValidStatus validStatus) {
      this.validStatus = validStatus;
   }
}
