// --- Auto Generated by BanTanger ---
package com.bantanger.api.admin.response;

import com.bantanger.common.enums.ValidStatus;
import com.bantanger.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;

@Schema
public class AdminUserResponse extends AbstractJpaResponse {
   @Schema(
         title = "手机号"
   )
   private String phone;

   @Schema(
         title = "用户名"
   )
   private String username;

   @Schema(
         title = "部门ID"
   )
   private Long departmentId;

   @Schema(
         title = "额外信息"
   )
   private String extraInfo;

   @Schema(
         title = "validStatus"
   )
   private ValidStatus validStatus;

   public String getPhone() {
      return phone;
   }

   public void setPhone(String phone) {
      this.phone = phone;
   }

   public String getUsername() {
      return username;
   }

   public void setUsername(String username) {
      this.username = username;
   }

   public Long getDepartmentId() {
      return departmentId;
   }

   public void setDepartmentId(Long departmentId) {
      this.departmentId = departmentId;
   }

   public String getExtraInfo() {
      return extraInfo;
   }

   public void setExtraInfo(String extraInfo) {
      this.extraInfo = extraInfo;
   }

   public ValidStatus getValidStatus() {
      return validStatus;
   }

   public void setValidStatus(ValidStatus validStatus) {
      this.validStatus = validStatus;
   }
}
