// --- Auto Generated by BanTanger ---
package com.bantanger.domain.asset.record.repository;

import com.bantanger.domain.asset.record.AssetInOutRecord;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface AssetInOutRecordRepository extends BaseRepository<AssetInOutRecord, Long> {
}
