// --- Auto Generated by BanTanger ---
package com.bantanger.domain.asset.record.repository;

import com.bantanger.domain.asset.record.AssetRecordDetail;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface AssetRecordDetailRepository extends BaseRepository<AssetRecordDetail, Long> {
}
