// --- Auto Generated by BanTanger ---
package com.bantanger.api.trade.orderlifecycle.response;

import com.bantanger.common.constants.ValidStatus;
import com.bantanger.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;

@Schema
public class OrderLifecycleResponse extends AbstractJpaResponse {
   @Schema(
         title = "唯一流水号"
   )
   private Long flowNo;

   @Schema(
         title = "操作类型"
   )
   private Integer operateType;

   @Schema(
         title = "额外信息"
   )
   private String remark;

   @Schema(
         title = "操作人"
   )
   private String operateUser;

   @Schema(
         title = "validStatus"
   )
   private ValidStatus validStatus;

   public Long getFlowNo() {
      return flowNo;
   }

   public void setFlowNo(Long flowNo) {
      this.flowNo = flowNo;
   }

   public Integer getOperateType() {
      return operateType;
   }

   public void setOperateType(Integer operateType) {
      this.operateType = operateType;
   }

   public String getRemark() {
      return remark;
   }

   public void setRemark(String remark) {
      this.remark = remark;
   }

   public String getOperateUser() {
      return operateUser;
   }

   public void setOperateUser(String operateUser) {
      this.operateUser = operateUser;
   }

   public ValidStatus getValidStatus() {
      return validStatus;
   }

   public void setValidStatus(ValidStatus validStatus) {
      this.validStatus = validStatus;
   }
}
