// --- Auto Generated by BanTanger ---
package com.bantanger.domain.asset.warehouse.repository;

import com.bantanger.domain.asset.warehouse.Warehouse;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface WarehouseRepository extends BaseRepository<Warehouse, Long> {
}
