// --- Auto Generated by BanTanger ---
package com.bantanger.domain.template.selectdict.repository;

import com.bantanger.domain.template.selectdict.SelectDict;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface SelectDictRepository extends BaseRepository<SelectDict, Long> {
}
