// --- Auto Generated by BanTanger ---
package com.bantanger.domain.message.template.repository;

import com.bantanger.domain.message.template.MessageTemplate;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;
import java.util.Optional;

public interface MessageTemplateRepository extends BaseRepository<MessageTemplate, Long> {

    /**
     * 根据模板编码查询模板
     * @param templateCode
     * @return
     */
    Optional<MessageTemplate> findByTemplateCode(String templateCode);
}
