// --- Auto Generated by BanTanger ---
package com.bantanger.domain.permission.repository;

import com.bantanger.domain.permission.role.RoleResourceRef;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface RoleResourceRefRepository extends BaseRepository<RoleResourceRef, Long> {
}
