// --- Auto Generated by BanTanger ---
package com.bantanger.domain.permission.resource.repository;

import com.bantanger.domain.permission.resource.Resource;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface ResourceRepository extends BaseRepository<Resource, Long> {
}
