// --- Auto Generated by BanTanger ---
package com.bantanger.domain.user.service;

import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.user.creator.UserAccountCreator;
import com.bantanger.domain.user.query.UserAccountQuery;
import com.bantanger.domain.user.updater.UserAccountUpdater;
import com.bantanger.domain.user.vo.UserAccountVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface IUserAccountService {
   /**
    * create
    */
   Long createUserAccount(UserAccountCreator creator);

   /**
    * update
    */
   void updateUserAccount(UserAccountUpdater updater);

   /**
    * valid
    */
   void validUserAccount(Long id);

   /**
    * invalid
    */
   void invalidUserAccount(Long id);

   /**
    * findById
    */
   UserAccountVO findById(Long id);

   /**
    * findByPage
    */
   Page<UserAccountVO> findByPage(PageRequestWrapper<UserAccountQuery> query);
}
