// --- Auto Generated by BanTanger ---
package com.bantanger.domain.user.service;

import com.bantanger.common.enums.CodeEnum;
import com.bantanger.common.exception.BusinessException;
import com.bantanger.common.model.PageRequestWrapper;
import com.bantanger.domain.user.UserAccount;
import com.bantanger.domain.user.creator.UserAccountCreator;
import com.bantanger.domain.user.mapper.UserAccountMapper;
import com.bantanger.domain.user.query.UserAccountQuery;
import com.bantanger.domain.user.repository.UserAccountRepository;
import com.bantanger.domain.user.updater.UserAccountUpdater;
import com.bantanger.domain.user.vo.UserAccountVO;
import com.bantanger.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class UserAccountServiceImpl implements IUserAccountService {
   private final UserAccountRepository userAccountRepository;

   /**
    * createImpl
    */
   @Override
   public Long createUserAccount(UserAccountCreator creator) {
      Optional<UserAccount> userAccount = EntityOperations.doCreate(userAccountRepository)
      .create(() -> UserAccountMapper.INSTANCE.dtoToEntity(creator))
      .update(e -> e.init())
      .execute();
      return userAccount.isPresent() ? userAccount.get().getId() : 0;
   }

   /**
    * update
    */
   @Override
   public void updateUserAccount(UserAccountUpdater updater) {
      EntityOperations.doUpdate(userAccountRepository)
      .loadById(updater.getId())
      .update(e -> updater.updateUserAccount(e))
      .execute();
   }

   /**
    * valid
    */
   @Override
   public void validUserAccount(Long id) {
      EntityOperations.doUpdate(userAccountRepository)
      .loadById(id)
      .update(e -> e.valid())
      .execute();
   }

   /**
    * invalid
    */
   @Override
   public void invalidUserAccount(Long id) {
      EntityOperations.doUpdate(userAccountRepository)
      .loadById(id)
      .update(e -> e.invalid())
      .execute();
   }

   /**
    * findById
    */
   @Override
   public UserAccountVO findById(Long id) {
      Optional<UserAccount> userAccount =  userAccountRepository.findById(id);
      return new UserAccountVO(userAccount.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
   }

   /**
    * findByPage
    */
   @Override
   public Page<UserAccountVO> findByPage(PageRequestWrapper<UserAccountQuery> query) {
      BooleanBuilder booleanBuilder = new BooleanBuilder();
      Page<UserAccount> page = userAccountRepository.findAll(booleanBuilder,
              PageRequest.of(query.getPage() - 1, query.getPageSize(),
              Sort.by(Sort.Direction.DESC, "createdAt")));
      return new PageImpl<>(page.getContent().stream().map(UserAccountVO::new)
              .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
   }
}
