// --- Auto Generated by BanTanger ---
package com.bantanger.domain.message.verify.repository;

import com.bantanger.domain.message.verify.VerifyRecord;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface VerifyRecordRepository extends BaseRepository<VerifyRecord, Long> {
}
