// --- Auto Generated by BanTanger ---
package com.bantanger.api.stock.seat.request;

import com.bantanger.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;

@Schema
public class SeatStockUpdateRequest implements Request {
   @Schema(
         title = "场次唯一标识"
   )
   private String showId;

   @Schema(
         title = "总库存数"
   )
   private Integer totalNum;

   @Schema(
         title = "已售数量"
   )
   private Integer soldNum;

   private Long id;

   public String getShowId() {
      return showId;
   }

   public void setShowId(String showId) {
      this.showId = showId;
   }

   public Integer getTotalNum() {
      return totalNum;
   }

   public void setTotalNum(Integer totalNum) {
      this.totalNum = totalNum;
   }

   public Integer getSoldNum() {
      return soldNum;
   }

   public void setSoldNum(Integer soldNum) {
      this.soldNum = soldNum;
   }

   public Long getId() {
      return id;
   }

   public void setId(long id) {
      this.id = id;
   }
}
