// --- Auto Generated by BanTanger ---
package com.bantanger.domain.user.mapper;

import com.bantanger.api.user.request.UserAccountCreateRequest;
import com.bantanger.api.user.request.UserAccountQueryRequest;
import com.bantanger.api.user.request.UserAccountUpdateRequest;
import com.bantanger.api.user.response.UserAccountResponse;
import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.domain.CustomMapper;
import com.bantanger.domain.user.UserAccount;
import com.bantanger.domain.user.creator.UserAccountCreator;
import com.bantanger.domain.user.query.UserAccountQuery;
import com.bantanger.domain.user.updater.UserAccountUpdater;
import com.bantanger.domain.user.vo.UserAccountVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
    uses = {
        GenericEnumMapper.class,
        DateMapper.class,
        CustomMapper.class
    }
)
public interface UserAccountMapper {

    UserAccountMapper INSTANCE = Mappers.getMapper(UserAccountMapper.class);

    UserAccount dtoToEntity(UserAccountCreator dto);

    UserAccountUpdater request2Updater(UserAccountUpdateRequest request);

    UserAccountCreator request2Dto(UserAccountCreateRequest request);

    UserAccountQuery request2Query(UserAccountQueryRequest request);

    UserAccountResponse vo2Response(UserAccountVO vo);

    default UserAccountResponse vo2CustomResponse(UserAccountVO vo) {
        UserAccountResponse response = vo2Response(vo);
        return response;
    }
}
