// --- Auto Generated by BanTanger ---
package com.bantanger.domain.user.mapper;

import com.bantanger.api.user.request.UserBaseCreateRequest;
import com.bantanger.api.user.request.UserBaseQueryRequest;
import com.bantanger.api.user.request.UserBaseUpdateRequest;
import com.bantanger.api.user.response.UserBaseResponse;
import com.bantanger.common.mapper.DateMapper;
import com.bantanger.common.mapper.GenericEnumMapper;
import com.bantanger.domain.user.UserBase;
import com.bantanger.domain.user.creator.UserBaseCreator;
import com.bantanger.domain.user.query.UserBaseQuery;
import com.bantanger.domain.user.updater.UserBaseUpdater;
import com.bantanger.domain.user.vo.UserBaseVO;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(
      uses = {
            GenericEnumMapper.class,
            DateMapper.class
      }
)
public interface UserBaseMapper {
   UserBaseMapper INSTANCE = Mappers.getMapper(UserBaseMapper.class);

   UserBase dtoToEntity(UserBaseCreator dto);

   UserBaseUpdater request2Updater(UserBaseUpdateRequest request);

   UserBaseCreator request2Dto(UserBaseCreateRequest request);

   UserBaseQuery request2Query(UserBaseQueryRequest request);

   UserBaseResponse vo2Response(UserBaseVO vo);

   default UserBaseResponse vo2CustomResponse(UserBaseVO vo) {
      UserBaseResponse response = vo2Response(vo);
      return response;
   }
}
