// --- Auto Generated by BanTanger ---
package com.bantanger.domain.trade.orderlifecycle.repository;

import com.bantanger.domain.trade.orderlifecycle.OrderLifecycle;
import com.bantanger.jpa.support.BaseRepository;
import java.lang.Long;

public interface OrderLifecycleRepository extends BaseRepository<OrderLifecycle, Long> {
}
